### ISSUE TITLE
Intermittent error: Suspension not allowed here

### ISSUE THREAD

**Issue by benjamingeer** [dasch-swiss/sipi#128]
Occasionally I get this error when serving a JPEG 2000 image in JPG format:

```
Sipi: Sipi image error at [/home/benjamingeer/git/Sipi/src/formats/SipiIOJpeg.cpp: 1064]: Suspension not allowed here
Sipi: Possibly socket closed by peer
```

**Comment by lrosenth** [comment]
Seems again an error that has to to with libjpeg not being thread safe. Is an error message from the jpeg library. Are all requests using the same image?

**Comment by benjamingeer** [comment]
I don't know whether it only happens with some images and not with others, but when I saw it, I was just reloading the same image again and again, and I saw the error message maybe once in ten requests. I've sent you the image in an email.

**Comment by lrosenth** [comment]
OK, this error is was produced if You click to fast, that is if You restart an image load before the old has been completely loaded. In this case the "old" transfer is being cancelled, which produces this (irritating) error message. Now libjpeg handles this correctly by throwing an exception which is caught later and just outputs an info that the connection has been dropped by the client.

**Comment by benjamingeer** [comment]
So this is a feature, not a bug? If so, can we catch this exception and ignore it, rather than printing an error message to the long?

**Comment by benjamingeer** [comment]
Or log it at `DEBUG` level?

**Comment by lrosenth** [comment]
OK, I changed the logging

**Comment by benjamingeer** [comment]
Which branch did you fix it on?
