### ISSUE TITLE
minimum version of kakadu?

### ISSUE THREAD

**Issue by nicolasfranck** [dasch-swiss/sipi#221]
I'm trying to build the Sipi from source.
I tried with an old version (v6_4_1-01131N), but that obviously didn't work ;-)

What version should I buy? Is the build tied to a specific version, or minimum version?

BTW. Is Kakadu required? As I read, not only jpeg2000 is supported as input.

**Comment by lrosenth** [comment]
I think we are using the newest version which is v7_A_2... With this version it should work without problems. you also need gcc >= 5.0

If You need help let us know! (lukas.rosenthaler@unibas.ch<mailto:lukas.rosenthaler@unibas.ch>)


Sent from my iPad

On 24 Nov 2017, at 20:33, Nicolas Franck <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm trying to build the Sipi from source.
I tried with an old version (v6_4_1-01131N), but that obviously didn't work ;-)

What version should I buy? Is it the build tied to a specific version, or minimum version?
