### ISSUE TITLE
segmentation fault after cleaning the generated output files 

### ISSUE THREAD

**Issue by SepidehAlassi** [dasch-swiss/sipi#250]
> Jul 18 18:35:51  Sipi[34917] <Error>: Kakadu-library: Error in Kakadu File Format Support:
> 	Unable to open output file, "../../Sipi/images/knora/S/FoDwzFYC4mG-Dx02rsoU0yk.jpx".
> [1]    34917 segmentation fault  ../../Sipi/local/bin/sipi --config config/sipi.knora-local-config.lua

I just cleaned the output files generated by Sipi in images/knora, in first try afterwards to import the data sipi fails with segmentation fault, in immediate second try it works.

It seams like a heap corruption!

**Comment by lrosenth** [comment]
We have to look at it... is the problemmin the context of knora? Is the sipi process allowed to write to the location and does it exist ?

Von meinem iPhone gesendet

Am 18.07.2018 um 09:43 schrieb Sepideh Alassi <notifications@github.com<mailto:notifications@github.com>>:


Jul 18 18:35:51 Sipi[34917] : Kakadu-library: Error in Kakadu File Format Support:
Unable to open output file, "../../Sipi/images/knora/S/FoDwzFYC4mG-Dx02rsoU0yk.jpx".
[1] 34917 segmentation fault ../../Sipi/local/bin/sipi --config config/sipi.knora-local-config.lua

I just cleaned the output files generated by Sipi in images/knora, in first try afterwards to import the data sipi fails with segmentation fault, in immediate second try it works.

It seams like a heap corruption!

**Comment by SepidehAlassi** [comment]
@lrosenth, it is not a problem in context of knora. It should be reproducible just with sipi. 

Sipi process is allowed to write to the location and  directory exists. 
To reproduce the issue:

1. let subdir_levels = 1, in a lua config file. 
2. run sipi as server with the config file
3. send conversion request to sipi with image files,  so that sipi creates subdirectories 'A-Z' and saves the output images in them
3. delete the subdirectories 'A-Z'
4. send the conversion request with image files again to sipi (it should fail here with segmentation fault!)
5. send the request immediately again, it will create subdirectories 'A-Z' and will save the output images.
