### ISSUE TITLE
Add Delete File Route

### ISSUE THREAD

**Issue by tobiasschweizer** [dasch-swiss/sipi#26]
Add a Lua script that deletes a file (thumb an full quality).

https://github.com/dhlab-basel/Knora/issues/67

Make sure that the request comes directly from Knora!

**Comment by benjamingeer** [comment]
> Make sure that the request comes directly from Knora!

This is the problem, I'm not sure how we should do this.

I'd like to rethink how Sipi can be controlled by a sysadmin. I'm not very happy with the current design, which requires you to log in using a web page.

I'd like to know how programs like this deal with the issue:

https://httpd.apache.org/docs/2.4/programs/apachectl.html

**Comment by tobiasschweizer** [comment]
But we haven't any permission control for the creation of images or files either. Everyone could fill up a Sipi server that is openly visible.

**Comment by benjamingeer** [comment]
> But we haven't any permission control for the creation of images or files either. Everyone could fill up a Sipi server that is openly visible.

Yes, that's a bug we need to fix. Another reason to rethink Sipi security.

**Comment by lrosenth** [comment]
As I always said: we should use for these operations a web-token with a shared secret between Sipi and Nora. Then Nora can provide the web-token to Sipi…

Lukas
On 28 Feb 2017, at 23:02, Benjamin Geer <notifications@github.com<mailto:notifications@github.com>> wrote:


But we haven't any permission control for the creation of images or files either. Everyone could fill up a Sipi server that is openly visible.

Yes, that's a bug we need to fix. Another reason to rethink Sipi security.

**Comment by tobiasschweizer** [comment]
Why would your daughter Nora need to know? :-)

**Comment by lrosenth** [comment]
Autocorrection…. ;-)

Lukas
Am 01.03.2017 um 00:13 schrieb Tobias Schweizer <notifications@github.com<mailto:notifications@github.com>>:


Why would your daughter Nora need to know? :-)

**Comment by benjamingeer** [comment]
I'd forgotten we talked about using JWT for this. Opened issue #138.
