### ISSUE TITLE
sqlite bug in while loop

### ISSUE THREAD

**Issue by ubunibas** [dasch-swiss/sipi#286]
There might be a problem using results in sqlite with prepared statements. Neither row = qry(project_name) or row = qry() in the while loop seems to return the next result
Example:
```
   db = sqlite('test.db', 'RO')
   qry = db << 'SELECT ip, access FROM access_control WHERE project = ?'
   row = qry(project_name)
   while (row) do
     print(row[0])
     row = qry(project_name)
   end
```
Thanks for checking, best
Martin

**Comment by lrosenth** [comment]
```
db = sqlite('test.db', 'RO')
   qry = db << 'SELECT ip, access FROM access_control WHERE project = ?'
   row = qry(project_name)
   while (row) do
     print(row[0])
     row = qry(project_name). <------- Hier ist ein Fehler drin: müsste heissen "row=qry()"
   end
```

**Comment by martrei** [comment]
Hallo Lukas,
hatte ich damals anscheinend auch probiert, siehe Kommentar über dem Code-Snippet, ausser du hast es getestet, dann glaube ich dir natürlich :-)
lg Martin

**Comment by lrosenth** [comment]
Bug fixed: reset of binding or prepared statement was at the wrong place. Test now includes this "feature". Still, the second qry() in the loop must not have a parameter!
