### ISSUE TITLE
Generate version string based on git tag for Sipi binary and Docker images

### ISSUE THREAD

**Issue by subotic** [dasch-swiss/sipi#297]
This version string should be used in the Sipi binary and the published Docker images.

CMake should generate the version string. A possible solution can be found here: https://www.mattkeeter.com/blog/2018-01-06-versioning/

**Comment by lrosenth** [comment]
we do have something in this direction. See:

https://github.com/dhlab-basel/Sipi/blob/9fe6c1e494511388305239a3c46b75f5c0b0db3e/CMakeLists.txt#L252-L269

**Comment by subotic** [comment]
Yes, thanks. I saw it. This is what gave me the idea to look further 😀
