### ISSUE TITLE
The permission returned by Lua function pre_flight is not valid: restrict:size=!128,128

### ISSUE THREAD

**Issue by benjamingeer** [dasch-swiss/sipi#301]
With the current `develop` version of Sipi, one of the Knora-Sipi integration tests fails with this error:

```
Sipi Error at [/sipi/src/SipiHttpServer.cpp: 281]: The permission returned by Lua function pre_flight is not valid: restrict:size=!128,128
```

Has the format of the return value of `pre_flight` changed?

**Comment by lrosenth** [comment]
I'll have a look at it!

**Comment by benjamingeer** [comment]
Has this been fixed?

**Comment by subotic** [comment]
Yes. The format for the return value of the pre_flight script changed. The fix was added [here](https://github.com/dasch-swiss/knora-api/commit/3368a3a2ddd815b88d1c48b5087960c8924c4bd0#diff-1d6a99317472af6ffbfb8ca828774bb7R144-R147).
