### ISSUE TITLE
Any route beginning with 'test' returns a PDF file containing a test image

### ISSUE THREAD

**Issue by benjamingeer** [dasch-swiss/sipi#315]
This caused the following problem: we changed the name of one of the Sipi test routes used in a Knora-Sipi integration test, but forgot to change the name of the route where it is called. The result was that the test called a nonexistent route. Sipi should have returned HTTP 404 (to let us know that the route does not exist), but it returned HTTP 200, because it returned the test PDF file instead.

**Comment by lrosenth** [comment]
Should be fixed
