### ISSUE TITLE
mimetype_consistency should also work with non-image files

### ISSUE THREAD

**Issue by benjamingeer** [dasch-swiss/sipi#316]
Currently. this method is implemented as `SipiImage::checkMimeTypeConsistency` and works only for images. It should be made more generic so  that it also works for non-image files.

**Comment by tobiasschweizer** [comment]
I think the method `checkMimeTypeConsistency` has to be moved out of `SipiImage` so it can be called for non image files. 

The method should already support non-image file extendsions:

https://github.com/dasch-swiss/sipi/blob/965a9e3dcb14a51bfc78c64262fe15db4fb1e557/src/SipiImage.cpp#L57-L64

**Comment by tobiasschweizer** [comment]
@lrosenth Could you give me a hand here?
