### ISSUE TITLE
No response when uploading certain PDF files

### ISSUE THREAD

**Issue by benjamingeer** [dasch-swiss/sipi#319]
Steps to reproduce:

1. Start Sipi using Knora's configuration:

```
$ cd knora-api/sipi
$ docker-compose up sipi
```

2. Upload [Programme_Colloque_Bertrand.pdf](https://github.com/dasch-swiss/sipi/files/4153419/Programme_Colloque_Bertrand.pdf) to Sipi using a valid Knora token:

```
curl -s -X POST -F filename=@Programme_Colloque_Bertrand.pdf 'http://localhost:1024/upload?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJLbm9yYSIsInN1YiI6Imh0dHA6Ly9yZGZoLmNoL3VzZXJzLzlYQkNyRFYzU1JhN2tTMVd3eW5CNFEiLCJhdWQiOlsiS25vcmEiLCJTaXBpIl0sImV4cCI6MTU4MzQxMzM4OCwiaWF0IjoxNTgwODIxMzg4LCJqdGkiOiJJOWVDS2dNSlM1UzF6M1VjVS1FYjFnIn0.nWAZR4rxznApuADgwyqNGcwcarRaQ1fQCjW0DDiTO-o'
```

Sipi accepts the connection but returns no response, and does not close the connection.

If the PDF file is first processed using PDFtk to fix potential errors in the file, Sipi accepts it and returns a response immediately: 
[Programme_Colloque_Bertrand-PDFTk-FIX.pdf](https://github.com/dasch-swiss/sipi/files/4153422/Programme_Colloque_Bertrand-PDFTk-FIX.pdf)

Moved from https://github.com/dasch-swiss/knora-api/issues/1581.

cc @loicjaouen @gfoo @mrivoal

**Comment by lrosenth** [comment]
I just tested it. I get as result:
```json
{
   "uploadedFiles": [
      {
         "temporaryUrl": "http://0.0.0.0:1024/tmp/JkXTnxolLiA-BNicTik471Z.pdf",
         "originalFilename": "Programme_Colloque_Bertrand-PDFTk-FIX.pdf",
         "fileType": "document",
         "internalFilename": "JkXTnxolLiA-BNicTik471Z.pdf"
      }
   ]
}
```

I can access the PDF then using the URL `http://0.0.0.0:1024/tmp/JkXTnxolLiA-BNicTik471Z.pdf`...
Im on the latest develop branch of knora using `docker-compose up sipi`.
To me this seems OK!

**Comment by loicjaouen** [comment]
thanks, we will cycle through release and test locally

**Comment by benjamingeer** [comment]
@lrosenth You tested the fixed version of the file (`Programme_Colloque_Bertrand-PDFTk-FIX.pdf`), not the original file (`Programme_Colloque_Bertrand.pdf`). Try the original version in the issue description above.

**Comment by benjamingeer** [comment]
I think this is my fault, you have to change the `curl` command to use the correct filename. Try this one:

```
curl -s -X POST -F filename=@Programme_Colloque_Bertrand.pdf 'http://localhost:1024/upload?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJLbm9yYSIsInN1YiI6Imh0dHA6Ly9yZGZoLmNoL3VzZXJzLzlYQkNyRFYzU1JhN2tTMVd3eW5CNFEiLCJhdWQiOlsiS25vcmEiLCJTaXBpIl0sImV4cCI6MTU4MzQxMzM4OCwiaWF0IjoxNTgwODIxMzg4LCJqdGkiOiJJOWVDS2dNSlM1UzF6M1VjVS1FYjFnIn0.nWAZR4rxznApuADgwyqNGcwcarRaQ1fQCjW0DDiTO-o'
```

**Comment by lrosenth** [comment]
@benjamingeer @loicjaouen I found the bug which was in the shttps-part reading a multipart data POST. If the data of a part ended with "\n", the boundary line was not recognized (which also starts with a "\n"...

@subotic Please add the new kakadu version to travis in order to pass the tests there... Then we can create a new sipi docker image. Besides upgrading the libraries and fixing this bug no new features have been added. Pullrequest will come when travis tests pass

**Comment by benjamingeer** [comment]
I think it would be worth considering not having Sipi implement its own HTTP server. I think there would be fewer bugs like this, and Sipi would become easier to maintain (less code to maintain).

**Comment by lrosenth** [comment]
Yes, in fact, I started SIPI with [moongoose](https://cesanta.com) from Cesanta, an open-source C++ server. However, I encountered so many problems that I had to decide to write my own. SIPI has some requirements which are difficult to do: All the image libraries must be able to directly write to the HTTP channel and – at the same time – use the cache (write/read). "Bending" the image libraries (kakadu, JPG, TIFF, PNG, JPG and webp) imposes some requirements to the webserver part.

From this experience, I would rather try to make a SIPI plugin/module for apache2 or nginx. But this will be a major undertaking... But I thought that I will have a look at this solution. Having a nifty SIPI-Plugin to nginx would be great ;-)

 An alternative would be to move SIPI to the JVM universe...

But for the moment I think we'll have to live with shttps. May be in summer in Corsica I'll find some time to have a in-depth look at alternatives.

**Comment by benjamingeer** [comment]
>  I would rather try to make a SIPI plugin/module for apache2 or nginx.

I was thinking the same thing. I think that would really make it easier to maintain Sipi over the long term.

**Comment by benjamingeer** [comment]
> An alternative would be to move SIPI to the JVM universe...

I could imagine doing just the image conversion in C++, and everything else in Scala. But the JVM’s native interface has some performance overhead that could be a problem.

**Comment by subotic** [comment]
@lrosenth which branch? Can you please make a PR?
