### ISSUE TITLE
make compile fails

### ISSUE THREAD

**Issue by albayenes** [dasch-swiss/sipi#330]
Hi,

make compile command fails on Ubuntu 16.04

sudo make compile command gives following error. How can i solve the issue?

```
docker run -it --rm -v :/sipi dhlabbasel/sipi-base:18.04 /bin/sh -c "mkdir -p /sipi/build-linux && cd /sipi/build-linux && cmake .. && make"
CMake Error: The source directory "/sipi" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
Makefile:36: recipe for target 'compile' failed
make: *** [compile] Error 1
```

**Comment by subotic** [comment]
Hi

Are you using `make compile`? If so, there seems to be a problem with ${PWD} not being substituted.

```
docker run -it --rm -v ${PWD}:/sipi dhlabbasel/sipi-base:18.04 /bin/sh -c "mkdir -p /sipi/build-linux && cd /sipi/build-linux && cmake .. && make"
```

**Comment by albayenes** [comment]
Thank you for your response. 

Yes I use `make compile` 

How can I solve the issue? Is the problem related to the code or my computer settings?

**Comment by subotic** [comment]
This looks like a problem in your environment. It should work on a Linux/Mac system. Windows is not supported, i.e., we never tried it out. You would need to rewrite the command line call to Docker and substitute `${PWD}` with the absolute path to the Sipi repository folder.

To be able to compile, you would also need to have a copy of the Kakadu J2K library, which is unfortunately closed source.
