### ISSUE TITLE
Lua Test Route luaexe/test2

### ISSUE THREAD

**Issue by tobiasschweizer** [dasch-swiss/sipi#34]
The path to the test image `Leaves8.tif` served by `luaexe/test2` is not set correctly when `imgroot` is set to `./images` because it resides in `./test_server/images`. 

This only works if `imgroot` is set to `./test_server/images` in the config file.

```
config.imgroot .. "/Leaves8.tif"
```

**Comment by benjamingeer** [comment]
I don't understand this issue. What is `luaexe`? Is this still relevant?

**Comment by tobiasschweizer** [comment]
I think `luaexe` is the route defined in `sipi.conf.lua`:

```
    {
        method = 'GET',
        route = '/luaexe/test1',
        script = 'test1.lua'
    },
    {
        method = 'GET',
        route = '/luaexe/test2',
        script = 'test2.lua'
    }
```
