### ISSUE TITLE
OpenJPEG support

### ISSUE THREAD

**Issue by julsraemy** [dasch-swiss/sipi#346]
After talking to some IIIF community members, some suggested that it would be great if SIPI could also supports [openJPEG](http://www.openjpeg.org/). 

1. Is it possible?
2. If yes, what would this require?

**Comment by jbaiter** [comment]
Just had a look at the source code, looks like I misread the documentation before complaining, it does have OpenJPEG support already, sorry!
https://github.com/dasch-swiss/sipi/blob/main/src/formats/SipiIOOpenJ2k.cpp

**Comment by julsraemy** [comment]
Maybe the documentation could be clearer though :) I will make myself a note.

**Comment by subotic** [comment]
Nope, "just" kakadu. The OpenJpeg2000 support was experimental and was much slower (at that time) than kakadu.
