### ISSUE TITLE
Automation of the documentation

### ISSUE THREAD

**Issue by julsraemy** [dasch-swiss/sipi#348]
A nice workflow actions that could be added to this repository is to automate the documentation on https://sipi.io as soon as changes occurs.

**Comment by kilchenmann** [comment]
I can implement the mkdocs deploy github action. It will run on each merge into main branch

**Comment by julsraemy** [comment]
> I can implement the mkdocs deploy github action. It will run on each merge into main branch

That would be great. Could you manually update it this time? I can't seem to install properly mkdocs with pip on my laptop...
