### ISSUE TITLE
Add other Tests (failure in serving file, not supported extension,etc.)

### ISSUE THREAD

**Issue by BiancoA** [dasch-swiss/sipi#50]
Sipi tests should cover some additional situations:
- the file extension requested is not supported,
- the file was not created (404 http status)
- ???

**Comment by BiancoA** [comment]
I am working on [this branch](https://github.com/dhlab-basel/Sipi/tree/tests/wrong_req)

**Comment by benjamingeer** [comment]
I'm making a Python-based testing framework, using [Pytest](http://doc.pytest.org/en/latest/), on the `python-test` branch.
