### ISSUE TITLE
Making a IIIF Request Providing dimension(s) for size is very slow on Mac

### ISSUE THREAD

**Issue by tobiasschweizer** [dasch-swiss/sipi#57]
When requesting a IIIF URL providing exact dimension(s), it sometimes takes SIPI very long to respond to the request:

http://localhost:1024/images/Leaves8.tif/full/83,/0/default.jpg

Manipulating the `width` can lead to much faster results. So I guess it could have something to do with size calculation and/or rounding. I experience these problems on Mac only. On my Ubuntu, it is fast.

**Comment by tobiasschweizer** [comment]
We especially experienced performance problems when running Sipi  with `config/sipi.knora-test-config.lua`.

In this case,  always the same file is served but the dimensions of the original files are requested resulting in distortion etc.

**Comment by lrosenth** [comment]
For large TIFF's, SIPI has to read the whole TIFF and then creating a reduced image by first expanding the image to a multiple of the required dimension and then averaging pixel values. This is a time consuming operation! If the image is in the cache, everyting should be fine. Use JPEG2000!

**Comment by tobiasschweizer** [comment]
But it is very fast on Ubuntu!

**Comment by BiancoA** [comment]
Just as a remainder: we are still compiling everything in Debug mode, so performances will change when Sipi will be compiled with -O2 or -O3
