### ISSUE TITLE
Report parsing errors for Lua scripts

### ISSUE THREAD

**Issue by tobiasschweizer** [dasch-swiss/sipi#69]
When a Lua scripts cannot be parsed correctly, Sipi should give a clear error message on startup.

**Comment by benjamingeer** [comment]
Can you provide a test case for this?

**Comment by tobiasschweizer** [comment]
I am thinking of a case in which one of the routes contains invalid code that leads to a parsing error.

At the moment, the routes are not parsed on startup. I think it would be good to parse them when they are added.
