### ISSUE TITLE
Allow a project to define what is a "restricted view" permission for a StillImageRepresentation

### ISSUE THREAD

**Issue by mrivoal** [dasch-swiss/sipi#77]
This issue is created following a discussion we had with Ben.

A **"restricted view" permission** for a `knora-base:StillImageRepresentation `may not be the same for every project and it may be a good thing to allow projects to define what is it they intend to display with this permission, e.g.:
- a blank page or a default image;
- an image with a watermark;
- no image at all, the user with a 'restricted view permission" will only be able to see the properties of a `knora-base:StillImageRepresentation` according to his permissions.

**Comment by benjamingeer** [comment]
Just talked about this with Lukas. This will be defined in Knora using the admin interface. It seems to us that "a blank page or a default image" is the same as "no image at all". We suggest these options:

* An image of a limited size.
* An image with a watermark.
* A "sorry, you can't see this image" image.

**Comment by mrivoal** [comment]
This would be just fine.
