### ISSUE TITLE
std::put_time in gcc 5

### ISSUE THREAD

**Issue by loicjaouen** [dasch-swiss/sipi#88]
when using gcc, build fails on:
this line: shttps/Logger.cpp::99 : 
```
*this << put_time(&tm, "[%Y-%m-%d %H-%M-%S] [") << LogLevelNames[msg_loglevel] << "] ";
```
with error:
```
'put_time' was not declared in this scope
```
because `std::put_time` is not included in gcc4.8 but in gcc5 ([according to this issue](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=54354)).

Sipi's main `README.md` says:
```
a working c++11 compiler (gcc >= v4.8 or clang)
```

A quick fix might be to test with gcc5 and update `README.md`.

**Comment by tobiasschweizer** [comment]
Ben is working on a replcement: https://github.com/dhlab-basel/Sipi/issues/86
